#! /usr/bin/env bash
export STEPZEN_ACCOUNT=$(cat ~/.stepzen/stepzen-config.yaml | shyaml get-value account)
export STEPZEN_HOST=stepzen
export STEPZEN_MODEL=breweries
export STEPZEN_APIKEY=$(cat ~/.stepzen/stepzen-config.yaml | shyaml get-value apikey)
export STEPZEN_ADMINKEY=$(cat ~/.stepzen/stepzen-config.yaml | shyaml get-value adminkey)
export STEPZEN_CONFIGFILE=stepzen/config.yaml
export APIGEE_ORG=geirs-purdy-project
export APIGEE_TEMPLATE_ZIP=apiproxy.zip
export APIGEE_BASEPATH=/graphql/breweries
export APIGEE_PROXYNAME=StepZen-Breweries-GraphQL
export APIGEE_TOKEN=$(gcloud auth print-access-token)

node --unhandled-rejections=strict index.js
